/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NbActionsheet {
    /**
    * 关闭显示
    */
    'close': () => void;
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle': string;
    /**
    * 是否需要遮罩
    */
    'mask': boolean;
    /**
    * 显示
    */
    'show': () => void;
  }
  interface NbActionsheetAttributes extends StencilHTMLAttributes {
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle'?: string;
    /**
    * 是否需要遮罩
    */
    'mask'?: boolean;
  }

  interface NbAffix {
    /**
    * 距离偏移量后触发（正数举例上沿，负数下沿）
    */
    'offset': number;
    /**
    * 计算举例的参照dom
    */
    'toTarget': any;
  }
  interface NbAffixAttributes extends StencilHTMLAttributes {
    /**
    * 距离偏移量后触发（正数举例上沿，负数下沿）
    */
    'offset'?: number;
    /**
    * 当固定状态发生变化对外发送事件
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 计算举例的参照dom
    */
    'toTarget'?: any;
  }

  interface NbCodeHighlight {
    /**
    * 代码内容
    */
    'code': string;
    /**
    * 代码类型
    */
    'lang': string;
  }
  interface NbCodeHighlightAttributes extends StencilHTMLAttributes {
    /**
    * 代码内容
    */
    'code'?: string;
    /**
    * 代码类型
    */
    'lang'?: string;
  }

  interface NbPagination {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide': boolean;
    /**
    * 当前页面
    */
    'current': number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage': 4 | 6 | 8;
    /**
    * 每页条数
    */
    'pagesize': number;
    /**
    * 总数据条数
    */
    'total': number;
  }
  interface NbPaginationAttributes extends StencilHTMLAttributes {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide'?: boolean;
    /**
    * 当前页面
    */
    'current'?: number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage'?: 4 | 6 | 8;
    /**
    * 当前页发生变化
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 每页条数
    */
    'pagesize'?: number;
    /**
    * 总数据条数
    */
    'total'?: number;
  }

  interface NbPlayground {}
  interface NbPlaygroundAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'NbActionsheet': Components.NbActionsheet;
    'NbAffix': Components.NbAffix;
    'NbCodeHighlight': Components.NbCodeHighlight;
    'NbPagination': Components.NbPagination;
    'NbPlayground': Components.NbPlayground;
  }

  interface StencilIntrinsicElements {
    'nb-actionsheet': Components.NbActionsheetAttributes;
    'nb-affix': Components.NbAffixAttributes;
    'nb-code-highlight': Components.NbCodeHighlightAttributes;
    'nb-pagination': Components.NbPaginationAttributes;
    'nb-playground': Components.NbPlaygroundAttributes;
  }


  interface HTMLNbActionsheetElement extends Components.NbActionsheet, HTMLStencilElement {}
  var HTMLNbActionsheetElement: {
    prototype: HTMLNbActionsheetElement;
    new (): HTMLNbActionsheetElement;
  };

  interface HTMLNbAffixElement extends Components.NbAffix, HTMLStencilElement {}
  var HTMLNbAffixElement: {
    prototype: HTMLNbAffixElement;
    new (): HTMLNbAffixElement;
  };

  interface HTMLNbCodeHighlightElement extends Components.NbCodeHighlight, HTMLStencilElement {}
  var HTMLNbCodeHighlightElement: {
    prototype: HTMLNbCodeHighlightElement;
    new (): HTMLNbCodeHighlightElement;
  };

  interface HTMLNbPaginationElement extends Components.NbPagination, HTMLStencilElement {}
  var HTMLNbPaginationElement: {
    prototype: HTMLNbPaginationElement;
    new (): HTMLNbPaginationElement;
  };

  interface HTMLNbPlaygroundElement extends Components.NbPlayground, HTMLStencilElement {}
  var HTMLNbPlaygroundElement: {
    prototype: HTMLNbPlaygroundElement;
    new (): HTMLNbPlaygroundElement;
  };

  interface HTMLElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement
    'nb-affix': HTMLNbAffixElement
    'nb-code-highlight': HTMLNbCodeHighlightElement
    'nb-pagination': HTMLNbPaginationElement
    'nb-playground': HTMLNbPlaygroundElement
  }

  interface ElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement;
    'nb-affix': HTMLNbAffixElement;
    'nb-code-highlight': HTMLNbCodeHighlightElement;
    'nb-pagination': HTMLNbPaginationElement;
    'nb-playground': HTMLNbPlaygroundElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
