/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NbActionsheet {
    /**
    * 关闭显示
    */
    'close': () => void;
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle': string;
    /**
    * 是否需要遮罩
    */
    'mask': boolean;
    /**
    * 显示
    */
    'show': () => void;
  }
  interface NbActionsheetAttributes extends StencilHTMLAttributes {
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle'?: string;
    /**
    * 是否需要遮罩
    */
    'mask'?: boolean;
  }

  interface NbCodeHighlight {
    /**
    * 代码内容
    */
    'code': string;
    /**
    * 代码类型
    */
    'lang': string;
  }
  interface NbCodeHighlightAttributes extends StencilHTMLAttributes {
    /**
    * 代码内容
    */
    'code'?: string;
    /**
    * 代码类型
    */
    'lang'?: string;
  }

  interface NbDemoSite {}
  interface NbDemoSiteAttributes extends StencilHTMLAttributes {}

  interface NbPagination {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide': boolean;
    /**
    * 当前页面
    */
    'current': number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage': 4 | 6 | 8;
    /**
    * 每页条数
    */
    'pagesize': number;
    /**
    * 总数据条数
    */
    'total': number;
  }
  interface NbPaginationAttributes extends StencilHTMLAttributes {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide'?: boolean;
    /**
    * 当前页面
    */
    'current'?: number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage'?: 4 | 6 | 8;
    /**
    * 当前页发生变化
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 每页条数
    */
    'pagesize'?: number;
    /**
    * 总数据条数
    */
    'total'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NbActionsheet': Components.NbActionsheet;
    'NbCodeHighlight': Components.NbCodeHighlight;
    'NbDemoSite': Components.NbDemoSite;
    'NbPagination': Components.NbPagination;
  }

  interface StencilIntrinsicElements {
    'nb-actionsheet': Components.NbActionsheetAttributes;
    'nb-code-highlight': Components.NbCodeHighlightAttributes;
    'nb-demo-site': Components.NbDemoSiteAttributes;
    'nb-pagination': Components.NbPaginationAttributes;
  }


  interface HTMLNbActionsheetElement extends Components.NbActionsheet, HTMLStencilElement {}
  var HTMLNbActionsheetElement: {
    prototype: HTMLNbActionsheetElement;
    new (): HTMLNbActionsheetElement;
  };

  interface HTMLNbCodeHighlightElement extends Components.NbCodeHighlight, HTMLStencilElement {}
  var HTMLNbCodeHighlightElement: {
    prototype: HTMLNbCodeHighlightElement;
    new (): HTMLNbCodeHighlightElement;
  };

  interface HTMLNbDemoSiteElement extends Components.NbDemoSite, HTMLStencilElement {}
  var HTMLNbDemoSiteElement: {
    prototype: HTMLNbDemoSiteElement;
    new (): HTMLNbDemoSiteElement;
  };

  interface HTMLNbPaginationElement extends Components.NbPagination, HTMLStencilElement {}
  var HTMLNbPaginationElement: {
    prototype: HTMLNbPaginationElement;
    new (): HTMLNbPaginationElement;
  };

  interface HTMLElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement
    'nb-code-highlight': HTMLNbCodeHighlightElement
    'nb-demo-site': HTMLNbDemoSiteElement
    'nb-pagination': HTMLNbPaginationElement
  }

  interface ElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement;
    'nb-code-highlight': HTMLNbCodeHighlightElement;
    'nb-demo-site': HTMLNbDemoSiteElement;
    'nb-pagination': HTMLNbPaginationElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
