/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface NbActionsheet {
    /**
    * 关闭显示
    */
    'close': () => void;
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle'?: string;
    /**
    * 是否需要遮罩 0 不需要，其他数字代表透明度
    */
    'mask': number;
    /**
    * 显示
    */
    'show': () => void;
  }
  interface NbActionsheetAttributes extends StencilHTMLAttributes {
    /**
    * 展示标题内容 （不用title避免跟原生属性冲突）
    */
    'headTitle'?: string;
    /**
    * 是否需要遮罩 0 不需要，其他数字代表透明度
    */
    'mask'?: number;
  }

  interface NbAffix {
    'getStartFixedScrollTop': () => Promise<number>;
    /**
    * 直接返回是否处于固定状态
    */
    'isFixed': () => Promise<boolean>;
    /**
    * 距离偏移量后触发（正数举例上沿，负数下沿）
    */
    'offset': number;
    /**
    * 计算举例的参照dom
    */
    'relativeSelector'?: string;
    /**
    * 固定时候zindex值
    */
    'zIndex': number;
  }
  interface NbAffixAttributes extends StencilHTMLAttributes {
    /**
    * 距离偏移量后触发（正数举例上沿，负数下沿）
    */
    'offset'?: number;
    /**
    * 当固定状态发生变化对外发送事件
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 计算举例的参照dom
    */
    'relativeSelector'?: string;
    /**
    * 固定时候zindex值
    */
    'zIndex'?: number;
  }

  interface NbBadge {
    /**
    * 徽标底色
    */
    'bgColor': string;
    /**
    * 展示数字，0为隐藏
    */
    'count': number;
    /**
    * 不展示数字，显示点
    */
    'dot': boolean;
    /**
    * count的封顶数值超出则显示 maxCount+
    */
    'maxCount': number;
    /**
    * 位置偏移量
    */
    'offset': number;
    /**
    * 当count为0的时候也显示
    */
    'showZero': boolean;
  }
  interface NbBadgeAttributes extends StencilHTMLAttributes {
    /**
    * 徽标底色
    */
    'bgColor'?: string;
    /**
    * 展示数字，0为隐藏
    */
    'count'?: number;
    /**
    * 不展示数字，显示点
    */
    'dot'?: boolean;
    /**
    * count的封顶数值超出则显示 maxCount+
    */
    'maxCount'?: number;
    /**
    * 位置偏移量
    */
    'offset'?: number;
    /**
    * 当count为0的时候也显示
    */
    'showZero'?: boolean;
  }

  interface NbCanvasRadar {
    /**
    * 雷达线颜色
    */
    'borderColor': string;
    /**
    * 字体大小
    */
    'fontSize': number;
    /**
    * 角顶文案
    */
    'labelDataList': string[];
    /**
    * 背景色以及分值
    */
    'points': any;
    /**
    * 半径间隔数
    */
    'unit': number;
    /**
    * 画布宽高
    */
    'wh': [number, number];
  }
  interface NbCanvasRadarAttributes extends StencilHTMLAttributes {
    /**
    * 雷达线颜色
    */
    'borderColor'?: string;
    /**
    * 字体大小
    */
    'fontSize'?: number;
    /**
    * 角顶文案
    */
    'labelDataList'?: string[];
    /**
    * 背景色以及分值
    */
    'points'?: any;
    /**
    * 半径间隔数
    */
    'unit'?: number;
    /**
    * 画布宽高
    */
    'wh'?: [number, number];
  }

  interface NbCodeHighlight {
    /**
    * 代码内容
    */
    'code': string;
    /**
    * 代码类型
    */
    'lang': string;
  }
  interface NbCodeHighlightAttributes extends StencilHTMLAttributes {
    /**
    * 代码内容
    */
    'code'?: string;
    /**
    * 代码类型
    */
    'lang'?: string;
  }

  interface HtEmoji {
    /**
    * 表情分组
    */
    'group': string;
    /**
    * 表情名称
    */
    'type': string;
  }
  interface HtEmojiAttributes extends StencilHTMLAttributes {
    /**
    * 表情分组
    */
    'group'?: string;
    /**
    * 表情名称
    */
    'type'?: string;
  }

  interface HtRichtextParser {
    /**
    * 调试模式
    */
    'debug'?: false;
  }
  interface HtRichtextParserAttributes extends StencilHTMLAttributes {
    /**
    * 调试模式
    */
    'debug'?: false;
  }

  interface HtStock {
    /**
    * 详情对应id
    */
    'detailId': string;
    /**
    * 头部标题
    */
    'headTitle': string;
  }
  interface HtStockAttributes extends StencilHTMLAttributes {
    /**
    * 详情对应id
    */
    'detailId'?: string;
    /**
    * 头部标题
    */
    'headTitle'?: string;
  }

  interface HtSubject {
    /**
    * 详情对应id
    */
    'detailId': string;
    /**
    * 头部标题
    */
    'headTitle': string;
    /**
    * 摘要
    */
    'summary': string;
  }
  interface HtSubjectAttributes extends StencilHTMLAttributes {
    /**
    * 详情对应id
    */
    'detailId'?: string;
    /**
    * 头部标题
    */
    'headTitle'?: string;
    /**
    * 摘要
    */
    'summary'?: string;
  }

  interface HtTopic {
    /**
    * 详情对应id
    */
    'detailId': string;
    /**
    * 头部标题
    */
    'headTitle': string;
  }
  interface HtTopicAttributes extends StencilHTMLAttributes {
    /**
    * 详情对应id
    */
    'detailId'?: string;
    /**
    * 头部标题
    */
    'headTitle'?: string;
  }

  interface NbListItem {
    /**
    * 下边框, 0则不显示
    */
    'border': number;
    /**
    * 线条颜色
    */
    'color': string;
    /**
    * 设置单元高度
    */
    'height'?: number;
    /**
    * 短线条方向
    */
    'short'?: 'left' | 'right' | 'both';
    /**
    * 设置横线左右间距
    */
    'sideSpace'?: number;
    /**
    * 是否启用横滑操作开关
    */
    'slide': boolean;
  }
  interface NbListItemAttributes extends StencilHTMLAttributes {
    /**
    * 下边框, 0则不显示
    */
    'border'?: number;
    /**
    * 线条颜色
    */
    'color'?: string;
    /**
    * 设置单元高度
    */
    'height'?: number;
    /**
    * 短线条方向
    */
    'short'?: 'left' | 'right' | 'both';
    /**
    * 设置横线左右间距
    */
    'sideSpace'?: number;
    /**
    * 是否启用横滑操作开关
    */
    'slide'?: boolean;
  }

  interface NbList {
    /**
    * List之间的间距
    */
    'topSpace'?: number;
  }
  interface NbListAttributes extends StencilHTMLAttributes {
    /**
    * List之间的间距
    */
    'topSpace'?: number;
  }

  interface NbMarquee {
    /**
    * 跑动内容列表
    */
    'items'?: {
      key: number,
      text: string,
      time?: string,
      link: string
    }[];
    /**
    * 多少间隔动一次
    */
    'speed': number;
    /**
    * 跑马灯预设样式
    */
    'styleId': 'tow-row-66h';
  }
  interface NbMarqueeAttributes extends StencilHTMLAttributes {
    /**
    * 跑动内容列表
    */
    'items'?: {
      key: number,
      text: string,
      time?: string,
      link: string
    }[];
    /**
    * 多少间隔动一次
    */
    'speed'?: number;
    /**
    * 跑马灯预设样式
    */
    'styleId'?: 'tow-row-66h';
  }

  interface NbRefresh {
    /**
    * 自动执行一次上拉加载
    */
    'autoScrollLoad': boolean;
    /**
    * 获取 refresh 实例化对象
    */
    'getRefresh': () => Promise<any>;
    /**
    * 禁用下拉刷新
    */
    'lockRefresh': boolean;
    /**
    * 禁用上拉加载更多
    */
    'lockScrollLoad': boolean;
    /**
    * 上下拉动的阀值
    */
    'offset': number;
    /**
    * 下拉刷新文案方面的配置 参数	参数类型	默认值	说明 isWrapCssTranslate	Boolean	false	是否下拉时wrap（下拉区域不是内容区域，与scroll区分开）会跟随css translate contentdown	String	'下拉刷新'	下拉刷新默认提示 contentover	String	'释放刷新'	在超过阈值后的提示 contentrefresh	String	'加载中...'	正在刷新中的提示 contentsuccess	String	'刷新成功'	刷新成功后，结束前，成功状态的提示 contenterror	String	'刷新失败'	刷新成功后，结束前，失败状态的提示
    */
    'refreshOptions': object;
    /**
    * 下拉刷新文案方面的配置 参数	参数类型	默认值	说明 contentdown	String	'上拉显示更多'	上拉加载默认提示，一般默认情况会隐藏用不到它 contentrefresh	String	'加载中...'	上拉加载时的提示 contentnomore	String	'没有更多数据了'	没有更多数据时的提示 toTop	Object	默认配置	滚动到顶部的相关配置，图片的话请在css中修改 toTop.isEnable	Boolean	true	是否开启自动滚动到顶部 toTop.duration	Number	300	滚动到顶部的过渡时间 toTop.offset	Number	800	阈值，滚动超过多少距离后才会显示滚动到顶部按钮
    */
    'scrollLoadOptions': object;
  }
  interface NbRefreshAttributes extends StencilHTMLAttributes {
    /**
    * 自动执行一次上拉加载
    */
    'autoScrollLoad'?: boolean;
    /**
    * 禁用下拉刷新
    */
    'lockRefresh'?: boolean;
    /**
    * 禁用上拉加载更多
    */
    'lockScrollLoad'?: boolean;
    /**
    * 上下拉动的阀值
    */
    'offset'?: number;
    /**
    * 下拉刷新事件
    */
    'onRefresh'?: (event: CustomEvent) => void;
    /**
    * 上拉加载事件
    */
    'onScrollLoad'?: (event: CustomEvent) => void;
    /**
    * 下拉刷新文案方面的配置 参数	参数类型	默认值	说明 isWrapCssTranslate	Boolean	false	是否下拉时wrap（下拉区域不是内容区域，与scroll区分开）会跟随css translate contentdown	String	'下拉刷新'	下拉刷新默认提示 contentover	String	'释放刷新'	在超过阈值后的提示 contentrefresh	String	'加载中...'	正在刷新中的提示 contentsuccess	String	'刷新成功'	刷新成功后，结束前，成功状态的提示 contenterror	String	'刷新失败'	刷新成功后，结束前，失败状态的提示
    */
    'refreshOptions'?: object;
    /**
    * 下拉刷新文案方面的配置 参数	参数类型	默认值	说明 contentdown	String	'上拉显示更多'	上拉加载默认提示，一般默认情况会隐藏用不到它 contentrefresh	String	'加载中...'	上拉加载时的提示 contentnomore	String	'没有更多数据了'	没有更多数据时的提示 toTop	Object	默认配置	滚动到顶部的相关配置，图片的话请在css中修改 toTop.isEnable	Boolean	true	是否开启自动滚动到顶部 toTop.duration	Number	300	滚动到顶部的过渡时间 toTop.offset	Number	800	阈值，滚动超过多少距离后才会显示滚动到顶部按钮
    */
    'scrollLoadOptions'?: object;
  }

  interface NbModal {
    /**
    * 标题（不填则去掉头部区域）
    */
    'headTitle'?: string;
    /**
    * 当弹窗类型是 confirm 时取消按钮文案
    */
    'noText': string;
    /**
    * 当弹窗类型是 alert, confirm 时确认按钮文案
    */
    'okText': string;
    /**
    * 点击取消按钮对应的操作
    */
    'onNo': Function;
    /**
    * 点击确认按钮对应的操作
    */
    'onOk': Function;
    /**
    * 显示位置
    */
    'position': 'center';
    /**
    * 显示
    */
    'show': (type: any, opts?: {}) => Promise<any>;
    /**
    * 样式定义
    */
    'theme': string;
    /**
    * 弹窗类型
    */
    'type': 'alert' | 'confirm';
    /**
    * 可见开关
    */
    'visible': boolean;
  }
  interface NbModalAttributes extends StencilHTMLAttributes {
    /**
    * 标题（不填则去掉头部区域）
    */
    'headTitle'?: string;
    /**
    * 当弹窗类型是 confirm 时取消按钮文案
    */
    'noText'?: string;
    /**
    * 当弹窗类型是 alert, confirm 时确认按钮文案
    */
    'okText'?: string;
    /**
    * 点击取消按钮对应的操作
    */
    'onNo'?: Function;
    /**
    * 点击确认按钮对应的操作
    */
    'onOk'?: Function;
    /**
    * 显示位置
    */
    'position'?: 'center';
    /**
    * 样式定义
    */
    'theme'?: string;
    /**
    * 弹窗类型
    */
    'type'?: 'alert' | 'confirm';
    /**
    * 可见开关
    */
    'visible'?: boolean;
  }

  interface NbPagination {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide': boolean;
    /**
    * 当前页面
    */
    'current': number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage': 4 | 6 | 8;
    /**
    * 每页条数
    */
    'pagesize': number;
    /**
    * 总数据条数
    */
    'total': number;
  }
  interface NbPaginationAttributes extends StencilHTMLAttributes {
    /**
    * 当只有一页的时候自动隐藏
    */
    'autoHide'?: boolean;
    /**
    * 当前页面
    */
    'current'?: number;
    /**
    * 当分页太多时候限制前后显示页数
    */
    'limitPage'?: 4 | 6 | 8;
    /**
    * 当前页发生变化
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 每页条数
    */
    'pagesize'?: number;
    /**
    * 总数据条数
    */
    'total'?: number;
  }

  interface NbPlayground {}
  interface NbPlaygroundAttributes extends StencilHTMLAttributes {}

  interface NbPullToDo {
    /**
    * 展示内容选择器
    */
    'contentSelector': string;
    /**
    * 拉动限制高度
    */
    'dampHeight': number;
    /**
    * 禁用哪项功能 refresh: 下拉刷新 | more: 加载更多
    */
    'disable'?: 'refresh' | 'more';
    /**
    * 加载完毕
    */
    'done': () => Promise<boolean>;
    /**
    * 加载状态
    */
    'loading': boolean;
    /**
    * 没有更多数据了
    */
    'noMore': boolean;
    /**
    * 当浏览器是返回状态是否尝试回到上一次的位置 ID
    */
    'positionSaveId'?: string;
    /**
    * 获取上次位置
    */
    'restoreLastPosition': () => Promise<any>;
    /**
    * 实际滚动显示区块选择器
    */
    'wrapperSelector': string;
  }
  interface NbPullToDoAttributes extends StencilHTMLAttributes {
    /**
    * 展示内容选择器
    */
    'contentSelector'?: string;
    /**
    * 拉动限制高度
    */
    'dampHeight'?: number;
    /**
    * 禁用哪项功能 refresh: 下拉刷新 | more: 加载更多
    */
    'disable'?: 'refresh' | 'more';
    /**
    * 加载状态
    */
    'loading'?: boolean;
    /**
    * 没有更多数据了
    */
    'noMore'?: boolean;
    /**
    * 当上拉触发加载更多
    */
    'onMore'?: (event: CustomEvent) => void;
    /**
    * 当下拉成立触发事件
    */
    'onRefresh'?: (event: CustomEvent) => void;
    /**
    * 当浏览器是返回状态是否尝试回到上一次的位置 ID
    */
    'positionSaveId'?: string;
    /**
    * 实际滚动显示区块选择器
    */
    'wrapperSelector'?: string;
  }

  interface NbRollPicker {
    /**
    * 选项内容对齐方向
    */
    'align': 'left' | 'center' | 'right';
    /**
    * 默认选中项目的key值
    */
    'defaultKey'?: number;
    /**
    * 获取当前选中的选项的数据
    */
    'getCurrentItem': () => Promise<any>;
    /**
    * 选项内容列表
    */
    'items': any[];
  }
  interface NbRollPickerAttributes extends StencilHTMLAttributes {
    /**
    * 选项内容对齐方向
    */
    'align'?: 'left' | 'center' | 'right';
    /**
    * 默认选中项目的key值
    */
    'defaultKey'?: number;
    /**
    * 选项内容列表
    */
    'items'?: any[];
  }

  interface NbSearchBar {}
  interface NbSearchBarAttributes extends StencilHTMLAttributes {}

  interface NbSvgIcon {
    /**
    * 加入动画名称
    */
    'anim': 'rotate' | '';
    /**
    * svg 大小
    */
    'size': 'xs' | 's' | 'm' | 'l' | 'xl';
    /**
    * type 图标类型，不使用内置的话不需要设置
    */
    'type'?: string;
  }
  interface NbSvgIconAttributes extends StencilHTMLAttributes {
    /**
    * 加入动画名称
    */
    'anim'?: 'rotate' | '';
    /**
    * svg 大小
    */
    'size'?: 'xs' | 's' | 'm' | 'l' | 'xl';
    /**
    * type 图标类型，不使用内置的话不需要设置
    */
    'type'?: string;
  }

  interface NbSwitch {
    /**
    * 是否默认选中
    */
    'checked': boolean;
    /**
    * 开关背景颜色
    */
    'color': string;
    /**
    * 是否不可修改
    */
    'disabled': boolean;
    /**
    * 高度
    */
    'h': number;
    /**
    * 宽度
    */
    'w': number;
  }
  interface NbSwitchAttributes extends StencilHTMLAttributes {
    /**
    * 是否默认选中
    */
    'checked'?: boolean;
    /**
    * 开关背景颜色
    */
    'color'?: string;
    /**
    * 是否不可修改
    */
    'disabled'?: boolean;
    /**
    * 高度
    */
    'h'?: number;
    /**
    * 当状态发生改变
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 宽度
    */
    'w'?: number;
  }

  interface NbToast {
    /**
    * 消失延时时间 0 -> 不自动消失
    */
    'duration': number;
    /**
    * 最大显示宽度
    */
    'maxLength': number;
    /**
    * 显示位置
    */
    'position': 'center';
    /**
    * 显示
    */
    'show': (message?: string) => Promise<any>;
    /**
    * 样式定义
    */
    'theme': string;
    /**
    * 可见开关
    */
    'visible': boolean;
  }
  interface NbToastAttributes extends StencilHTMLAttributes {
    /**
    * 消失延时时间 0 -> 不自动消失
    */
    'duration'?: number;
    /**
    * 最大显示宽度
    */
    'maxLength'?: number;
    /**
    * 显示位置
    */
    'position'?: 'center';
    /**
    * 样式定义
    */
    'theme'?: string;
    /**
    * 可见开关
    */
    'visible'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'NbActionsheet': Components.NbActionsheet;
    'NbAffix': Components.NbAffix;
    'NbBadge': Components.NbBadge;
    'NbCanvasRadar': Components.NbCanvasRadar;
    'NbCodeHighlight': Components.NbCodeHighlight;
    'HtEmoji': Components.HtEmoji;
    'HtRichtextParser': Components.HtRichtextParser;
    'HtStock': Components.HtStock;
    'HtSubject': Components.HtSubject;
    'HtTopic': Components.HtTopic;
    'NbListItem': Components.NbListItem;
    'NbList': Components.NbList;
    'NbMarquee': Components.NbMarquee;
    'NbRefresh': Components.NbRefresh;
    'NbModal': Components.NbModal;
    'NbPagination': Components.NbPagination;
    'NbPlayground': Components.NbPlayground;
    'NbPullToDo': Components.NbPullToDo;
    'NbRollPicker': Components.NbRollPicker;
    'NbSearchBar': Components.NbSearchBar;
    'NbSvgIcon': Components.NbSvgIcon;
    'NbSwitch': Components.NbSwitch;
    'NbToast': Components.NbToast;
  }

  interface StencilIntrinsicElements {
    'nb-actionsheet': Components.NbActionsheetAttributes;
    'nb-affix': Components.NbAffixAttributes;
    'nb-badge': Components.NbBadgeAttributes;
    'nb-canvas-radar': Components.NbCanvasRadarAttributes;
    'nb-code-highlight': Components.NbCodeHighlightAttributes;
    'ht-emoji': Components.HtEmojiAttributes;
    'ht-richtext-parser': Components.HtRichtextParserAttributes;
    'ht-stock': Components.HtStockAttributes;
    'ht-subject': Components.HtSubjectAttributes;
    'ht-topic': Components.HtTopicAttributes;
    'nb-list-item': Components.NbListItemAttributes;
    'nb-list': Components.NbListAttributes;
    'nb-marquee': Components.NbMarqueeAttributes;
    'nb-refresh': Components.NbRefreshAttributes;
    'nb-modal': Components.NbModalAttributes;
    'nb-pagination': Components.NbPaginationAttributes;
    'nb-playground': Components.NbPlaygroundAttributes;
    'nb-pull-to-do': Components.NbPullToDoAttributes;
    'nb-roll-picker': Components.NbRollPickerAttributes;
    'nb-search-bar': Components.NbSearchBarAttributes;
    'nb-svg-icon': Components.NbSvgIconAttributes;
    'nb-switch': Components.NbSwitchAttributes;
    'nb-toast': Components.NbToastAttributes;
  }


  interface HTMLNbActionsheetElement extends Components.NbActionsheet, HTMLStencilElement {}
  var HTMLNbActionsheetElement: {
    prototype: HTMLNbActionsheetElement;
    new (): HTMLNbActionsheetElement;
  };

  interface HTMLNbAffixElement extends Components.NbAffix, HTMLStencilElement {}
  var HTMLNbAffixElement: {
    prototype: HTMLNbAffixElement;
    new (): HTMLNbAffixElement;
  };

  interface HTMLNbBadgeElement extends Components.NbBadge, HTMLStencilElement {}
  var HTMLNbBadgeElement: {
    prototype: HTMLNbBadgeElement;
    new (): HTMLNbBadgeElement;
  };

  interface HTMLNbCanvasRadarElement extends Components.NbCanvasRadar, HTMLStencilElement {}
  var HTMLNbCanvasRadarElement: {
    prototype: HTMLNbCanvasRadarElement;
    new (): HTMLNbCanvasRadarElement;
  };

  interface HTMLNbCodeHighlightElement extends Components.NbCodeHighlight, HTMLStencilElement {}
  var HTMLNbCodeHighlightElement: {
    prototype: HTMLNbCodeHighlightElement;
    new (): HTMLNbCodeHighlightElement;
  };

  interface HTMLHtEmojiElement extends Components.HtEmoji, HTMLStencilElement {}
  var HTMLHtEmojiElement: {
    prototype: HTMLHtEmojiElement;
    new (): HTMLHtEmojiElement;
  };

  interface HTMLHtRichtextParserElement extends Components.HtRichtextParser, HTMLStencilElement {}
  var HTMLHtRichtextParserElement: {
    prototype: HTMLHtRichtextParserElement;
    new (): HTMLHtRichtextParserElement;
  };

  interface HTMLHtStockElement extends Components.HtStock, HTMLStencilElement {}
  var HTMLHtStockElement: {
    prototype: HTMLHtStockElement;
    new (): HTMLHtStockElement;
  };

  interface HTMLHtSubjectElement extends Components.HtSubject, HTMLStencilElement {}
  var HTMLHtSubjectElement: {
    prototype: HTMLHtSubjectElement;
    new (): HTMLHtSubjectElement;
  };

  interface HTMLHtTopicElement extends Components.HtTopic, HTMLStencilElement {}
  var HTMLHtTopicElement: {
    prototype: HTMLHtTopicElement;
    new (): HTMLHtTopicElement;
  };

  interface HTMLNbListItemElement extends Components.NbListItem, HTMLStencilElement {}
  var HTMLNbListItemElement: {
    prototype: HTMLNbListItemElement;
    new (): HTMLNbListItemElement;
  };

  interface HTMLNbListElement extends Components.NbList, HTMLStencilElement {}
  var HTMLNbListElement: {
    prototype: HTMLNbListElement;
    new (): HTMLNbListElement;
  };

  interface HTMLNbMarqueeElement extends Components.NbMarquee, HTMLStencilElement {}
  var HTMLNbMarqueeElement: {
    prototype: HTMLNbMarqueeElement;
    new (): HTMLNbMarqueeElement;
  };

  interface HTMLNbRefreshElement extends Components.NbRefresh, HTMLStencilElement {}
  var HTMLNbRefreshElement: {
    prototype: HTMLNbRefreshElement;
    new (): HTMLNbRefreshElement;
  };

  interface HTMLNbModalElement extends Components.NbModal, HTMLStencilElement {}
  var HTMLNbModalElement: {
    prototype: HTMLNbModalElement;
    new (): HTMLNbModalElement;
  };

  interface HTMLNbPaginationElement extends Components.NbPagination, HTMLStencilElement {}
  var HTMLNbPaginationElement: {
    prototype: HTMLNbPaginationElement;
    new (): HTMLNbPaginationElement;
  };

  interface HTMLNbPlaygroundElement extends Components.NbPlayground, HTMLStencilElement {}
  var HTMLNbPlaygroundElement: {
    prototype: HTMLNbPlaygroundElement;
    new (): HTMLNbPlaygroundElement;
  };

  interface HTMLNbPullToDoElement extends Components.NbPullToDo, HTMLStencilElement {}
  var HTMLNbPullToDoElement: {
    prototype: HTMLNbPullToDoElement;
    new (): HTMLNbPullToDoElement;
  };

  interface HTMLNbRollPickerElement extends Components.NbRollPicker, HTMLStencilElement {}
  var HTMLNbRollPickerElement: {
    prototype: HTMLNbRollPickerElement;
    new (): HTMLNbRollPickerElement;
  };

  interface HTMLNbSearchBarElement extends Components.NbSearchBar, HTMLStencilElement {}
  var HTMLNbSearchBarElement: {
    prototype: HTMLNbSearchBarElement;
    new (): HTMLNbSearchBarElement;
  };

  interface HTMLNbSvgIconElement extends Components.NbSvgIcon, HTMLStencilElement {}
  var HTMLNbSvgIconElement: {
    prototype: HTMLNbSvgIconElement;
    new (): HTMLNbSvgIconElement;
  };

  interface HTMLNbSwitchElement extends Components.NbSwitch, HTMLStencilElement {}
  var HTMLNbSwitchElement: {
    prototype: HTMLNbSwitchElement;
    new (): HTMLNbSwitchElement;
  };

  interface HTMLNbToastElement extends Components.NbToast, HTMLStencilElement {}
  var HTMLNbToastElement: {
    prototype: HTMLNbToastElement;
    new (): HTMLNbToastElement;
  };

  interface HTMLElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement
    'nb-affix': HTMLNbAffixElement
    'nb-badge': HTMLNbBadgeElement
    'nb-canvas-radar': HTMLNbCanvasRadarElement
    'nb-code-highlight': HTMLNbCodeHighlightElement
    'ht-emoji': HTMLHtEmojiElement
    'ht-richtext-parser': HTMLHtRichtextParserElement
    'ht-stock': HTMLHtStockElement
    'ht-subject': HTMLHtSubjectElement
    'ht-topic': HTMLHtTopicElement
    'nb-list-item': HTMLNbListItemElement
    'nb-list': HTMLNbListElement
    'nb-marquee': HTMLNbMarqueeElement
    'nb-refresh': HTMLNbRefreshElement
    'nb-modal': HTMLNbModalElement
    'nb-pagination': HTMLNbPaginationElement
    'nb-playground': HTMLNbPlaygroundElement
    'nb-pull-to-do': HTMLNbPullToDoElement
    'nb-roll-picker': HTMLNbRollPickerElement
    'nb-search-bar': HTMLNbSearchBarElement
    'nb-svg-icon': HTMLNbSvgIconElement
    'nb-switch': HTMLNbSwitchElement
    'nb-toast': HTMLNbToastElement
  }

  interface ElementTagNameMap {
    'nb-actionsheet': HTMLNbActionsheetElement;
    'nb-affix': HTMLNbAffixElement;
    'nb-badge': HTMLNbBadgeElement;
    'nb-canvas-radar': HTMLNbCanvasRadarElement;
    'nb-code-highlight': HTMLNbCodeHighlightElement;
    'ht-emoji': HTMLHtEmojiElement;
    'ht-richtext-parser': HTMLHtRichtextParserElement;
    'ht-stock': HTMLHtStockElement;
    'ht-subject': HTMLHtSubjectElement;
    'ht-topic': HTMLHtTopicElement;
    'nb-list-item': HTMLNbListItemElement;
    'nb-list': HTMLNbListElement;
    'nb-marquee': HTMLNbMarqueeElement;
    'nb-refresh': HTMLNbRefreshElement;
    'nb-modal': HTMLNbModalElement;
    'nb-pagination': HTMLNbPaginationElement;
    'nb-playground': HTMLNbPlaygroundElement;
    'nb-pull-to-do': HTMLNbPullToDoElement;
    'nb-roll-picker': HTMLNbRollPickerElement;
    'nb-search-bar': HTMLNbSearchBarElement;
    'nb-svg-icon': HTMLNbSvgIconElement;
    'nb-switch': HTMLNbSwitchElement;
    'nb-toast': HTMLNbToastElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
